export enum ROUTE_NAME {
  ADDRESS = "MAIN.ADDRESS",
  CART = "MAIN.CART",
  CHECKOUT = "CHECKOUT",
  HOME = "MAIN.HOME",
  MAP_SELECTOR = "MAP.SELECTOR",
  PIZZA_DETAILS = "PIZZA.DETAILS",
  PROMO_DETAILS = "PROMO.DETAILS",
  ORDERS = "ORDERS",
}
