export enum ROUTE_NAME {
  ADDRESS = "MAIN.ADDRESS",
  CART = "MAIN.CART",
  CHECKOUT = "CHECKOUT",
  HOME = "MAIN.HOME",
  MAP_SELECTOR = "MAP.SELECTOR",
  OFFER_DETAILS = "OFFER.DETAILS",
  ORDERS = "ORDERS",
}
